### ISSUE TITLE
[ERROR] > Error parsing iCal data (69)

### ISSUE THREAD

**Issue by spady7** [andrewramsay/ical_to_gcal_sync#12]
HI, I was testing this great script and, let me say day 1 of testing, all was good.
Day 2 of testing i start to get this error "[ERROR] > Error parsing iCal data (69)" taken from txt log file.

What is wrong on parsing ical object?
Is there a way to troubleshoot it?
Regards

**Comment by andrewramsay** [comment]
Well, the value in parentheses in that log message is supposed to be the string representation of the Exception object that was raised during parsing, but "69" is not as helpful as I expected it would be! 

The script uses [python_ics](https://github.com/intrepidcs/python_ics/) to do the parsing, so that's where the exception is occurring. You could try simply removing the try/except block in get_current_events and just have ```cal = ics.Calendar(resp.text)```, that should let you see the full exception. I'm guessing it's either a bad response from the calendar URL or there's some event in the calendar with attributes that it can't parse.

**Comment by spady7** [comment]
Unfort. no code let me undestand. here is the output:

2020-03-19 16:12:08,165|[DEBUG] > Loading credentials
2020-03-19 16:12:08,844|[INFO] > Retrieving events from Google Calendar
2020-03-19 16:12:08,844|[DEBUG] Retrieving Google Calendar events
2020-03-19 16:12:09,153|[INFO] > Found 1 upcoming events in Google Calendar (single page)
2020-03-19 16:12:09,153|[INFO] > Retrieving events from iCal feed

Here the snippet of code:

`def get_current_events():
    """Retrieves data from iCal iCal feed and returns an ics.Calendar object 
    containing the parsed data.

    Returns the parsed Calendar object or None if an error occurs.
    """
    resp = requests.get(ICAL_FEED)
    #print (resp.text)
    if resp.status_code != 200:
        logger.error('> Error retrieving iCal feed!')
        return None

    #try:
        cal = ics.Calendar(resp.text)
    #except Exception as e:
        logger.error('> Error parsing iCal data ({})'.format(e))
     #   return None

   # return cal`

**Comment by spady7** [comment]
IF is helpful a can post you a calendar.ics file if you want have a look if there are some attributes that cannot be parsed.

**Comment by andrewramsay** [comment]
If you're not comfortable editing the code and you don't mind sharing the ics file then sure, I can have a look.

**Comment by spady7** [comment]
Sure, where can i share?

**Comment by andrewramsay** [comment]
I think you should just be able to do it on here, try to drag and drop the file into your comment box.

**Comment by spady7** [comment]
[calendar.ics.zip](https://github.com/andrewramsay/ical_to_gcal_sync/files/4355362/calendar.ics.zip)

**Comment by andrewramsay** [comment]
OK, it's having trouble parsing some of the non-ASCII characters because it is not being treated as being UTF-8 encoded for some reason (if I load the file with the encoding set explicitly it parses fine). 

Could you try editing that method so it looks like this?
```python
resp = requests.get(ICAL_FEED)
if resp.status_code != 200:
    logger.error('> Error retrieving iCal feed!')
    return None

print('original encoding is {}'.format(resp.encoding))
resp.encoding = 'utf-8'
cal = ics.Calendar(resp.text)
return cal
```
and then try running it again? This should print what the requests module thinks the original encoding is, and then force it to use UTF-8 instead. That might make it parse correctly.

**Comment by spady7** [comment]
Some errors:

> original encoding is utf-8
Traceback (most recent call last):
  File "ical_to_gcal_sync.py", line 160, in <module>
    ical_cal = get_current_events()
  File "ical_to_gcal_sync.py", line 53, in get_current_events
    cal = ics.Calendar(resp.text)
  File "/usr/local/lib/python3.7/site-packages/ics/icalendar.py", line 68, in __init__
    self._populate(container[0])  # Use first calendar
  File "/usr/local/lib/python3.7/site-packages/ics/component.py", line 59, in _populate
    extractor.function(self, lines)  # Send a list or empty list
  File "/usr/local/lib/python3.7/site-packages/ics/icalendar.py", line 207, in events
    calendar.events = set(map(event_factory, lines))
  File "/usr/local/lib/python3.7/site-packages/ics/icalendar.py", line 206, in event_factory
    return Event._from_container(x, tz=calendar._timezones)
  File "/usr/local/lib/python3.7/site-packages/ics/component.py", line 31, in _from_container
    k._populate(container)
  File "/usr/local/lib/python3.7/site-packages/ics/component.py", line 62, in _populate
    extractor.function(self, lines[0])  # Send the element
  File "/usr/local/lib/python3.7/site-packages/ics/event.py", line 486, in start
    event.begin = iso_to_arrow(line, tz_dict)
  File "/usr/local/lib/python3.7/site-packages/ics/utils.py", line 76, in iso_to_arrow
    naive = arrow_get(val).naive
  File "/usr/local/lib/python3.7/site-packages/ics/utils.py", line 54, in arrow_get
    return arrow.get(string, DATE_FORMATS[len(string)])
KeyError: 69

**Comment by andrewramsay** [comment]
Ah that's helpful! It's actually not the text encoding, that's being picked up as UTF-8. It's date parsing! And it explains where that "69" came from. 

I think this is a bug in the version of the ics module in the requirements.txt for this script. Can you try updating it to the latest 0.7 version with "pip3 install --upgrade ics"? I tried that and it seems to parse it successfully afterwards. If that works for you I'll update the requirements.txt version too.

**Comment by spady7** [comment]
I think this issue is solved, updating ics module. 
Now raised another issue, but i don't think is related to script.
Here errors:

> Traceback (most recent call last):
  File "ical_to_gcal_sync.py", line 255, in <module>
    service.events().insert(calendarId=CALENDAR_ID, body=gcal_event).execute()
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 409 when requesting https://www.googleapis.com/calendar/v3/calendars/email@gmail.com/events?alt=json returned "The requested identifier already exists.">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ical_to_gcal_sync.py", line 258, in <module>
    service.events().update(calendarId=CALENDAR_ID, eventId=gcal_event['id'], body=gcal_event).execute()
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/calendar/v3/calendars/email@gmail.com/events/040000008200e00074c5b7101a82e00800000000236ccd1841f8d501000000000000000010000000a51abaa9bc790e4ba801a92af1f831bb15976224001598054400?alt=json returned "Forbidden">


I tried to google i little bit and seams others had this issue but my google API quota are set to 1.000.000 so is not possibile that i reached "per day usage".
Have you ever get this issue?

**Comment by spady7** [comment]
![Schermata 2020-03-19 alle 17 25 59](https://user-images.githubusercontent.com/31621633/77089897-b5c29e00-6a06-11ea-8dba-6093bbd7cba2.png)

**Comment by spady7** [comment]
The weird thing is if a try to change ICAL URL (for istance another calendar, collegue ones) it works!!! Does the script store something inside my computer? I mean, i've already tried to delete "ical_to_gcal_sync.pckl" file and generata a new psw. I've also deleted project at API console e created as new one. Always get same error ( this error was present by this moorning)

**Comment by andrewramsay** [comment]
I'm not sure exactly what's happening here, but it *might* be something to do with the really annoying way that "deleting" events from a Google Calendar really just hides them. I've had some strange problems and error messages before where it was trying to create a new event that actually still existed but was not visible. 

Have you tried either a) going to your Google calendar settings > "Bin" page and deleting all the hidden items that are probably listed there or b) if you're not using your primary calendar, you could simply delete it and create a new one (and if you are using the primary calendar, try creating a separate one and update the CALENDAR_ID in the config).

(btw you may want to edit the traceback with the HTTP errors if you don't want to expose your email address!)

**Comment by spady7** [comment]
You right!!!
a) KO!!....Bin was already empty (tried/check many times to be sure was empty) but issue still present
b) GOOD!!!!...tried to create a new calendar and sync iCal with it and everything goes well!!

I suppose that items are not complete deleted! that could be the root cause. Maybe there are some command API that can check and make a Raw delete.
What you think?

Anyway, very good job!!
Regards

**Comment by andrewramsay** [comment]
I don't think there is a way to force a full delete unfortunately, I've looked through the Calendar API docs a few times and couldn't find anything in there that would allow it. I hope they do add that at some point as it would make cleaning up old events much simpler.

Hope things continue working with the new calendar instance!
